name: topkiddo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  #  flutter_svg: ^0.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^0.5.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_screenutil: ^4.0.3+1
  # flutter_svg: ^0.17.4
  fluttertoast: ^8.0.2
  http: ^0.12.1
  
  # flutter_facebook_auth: ^2.0.2
  #firebase_core: ^0.7.0
  firebase_auth: any
  google_sign_in: ^4.4.4+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background/Bg_Ipad.jpg
    - assets/images/background/bg_iphone.jpg
    - assets/images/background/BG-ipad-full.jpg
    - assets/images/background/BG-iphone-full.jpg
    - assets/images/background/foriPadBG-compressed.jpg
    - assets/images/background/foriPhoneBG-compressed.jpg
    - assets/images/button/add_short.png
    - assets/images/button/back-button.png
    - assets/images/button/home-button.png
    - assets/images/button/setting-button.png
    - assets/images/button/musicon-button.png
    - assets/images/button/bar-long.png
    - assets/images/button/close-button.png
    - assets/images/button/enlish-flag.png
    - assets/images/button/menu-button.png
    - assets/images/button/vietnames-flag.png
    - assets/images/button/logout.png
    - assets/images/lesson/6thang.png
    - assets/images/lesson/12thang.png
    - assets/images/lesson/trondoi.png
    - assets/images/lesson/buynow-button.png
    - assets/images/lesson/lesson-active.png
    - assets/images/lesson/disable-board.png
    - assets/images/lesson/text-completed.png
    - assets/images/lesson/text-hoanthanh.png
    - assets/images/lesson/ip-full-board-white.png
    - assets/images/lesson/ipad-full-board-white.png
    - assets/images/login_page/fb-button.png
    - assets/images/login_page/g+button.png
    - assets/images/login_page/loginboard.png
    - assets/images/login_page/loginbutton1.png
    - assets/images/login_page/main-loginbutton.png
    - assets/images/login_page/main-newuserbutton.png
    - assets/images/login_page/new-userbutton.png
    - assets/images/login_page/register-button.png
    - assets/images/login_page/registerboard.png
    - assets/images/topic/choose-button.png
    - assets/images/topic/designed-courses.png
    - assets/images/topic/expressions.png
    - assets/images/topic/flexible.png
    - assets/images/namegame.png
    - assets/images/button/library-button.png
    - assets/images/unit/course-board.png
    - assets/images/unit/course1.png
    - assets/images/unit/course2.png
    - assets/images/unit/coursetick.png
    - assets/images/unit/language-flag.png
    - assets/images/unit/bar-plus.png
    - assets/images/languages/2-em-be.png
    - assets/images/languages/babe1.png
    - assets/images/languages/babe2.png
    - assets/images/languages/line-chine.png
    - assets/images/languages/line1.png
    - assets/images/flashcard/image1.jpg
    - assets/images/flashcard/image2.jpg
    - assets/images/flashcard/image3.jpg
    - assets/images/flashcard/image4.jpg
    - assets/images/flashcard/image5.jpg
    - assets/images/flashcard/image6.jpg
    - assets/images/flashcard/image7.jpg
    - assets/images/flashcard/image8.jpg
    - assets/images/firework/firework1.png
    - assets/images/firework/firework2.png
    - assets/images/firework/firework3.png
    - assets/images/firework/firework4.png
    - assets/images/firework/firework5.png
    - assets/images/firework/firework6.png
    - assets/images/firework/firework7.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: UTMCooperBlack
      fonts:
        - asset: assets/fonts/UTMCooperBlack.ttf
          weight: 900
    - family: UTMCooperBlackItalic
      fonts:
        - asset: assets/fonts/UTMCooperBlackItalic.ttf
          style: italic
          weight: 900
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
